# nixpacks.toml

[phases.setup]
# A comprehensive list of system dependencies for OpenCV and Ultralytics
aptPkgs = ["libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 