# nixpacks.toml

[phases.setup]
# Use the Nix package manager directly for robust, guaranteed dependency handling.
# This is the definitive solution for providing system libraries on Railway.
# `libglvnd` is the specific package for making libGL.so.1 discoverable at runtime.
nixPkgs = [
  "python312",
  "libglvnd",
  "glib"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 