# nixpacks.toml

[phases.setup]
# A comprehensive and definitive list of system packages required by the application.
nixPkgs = [
  "python312",
  "libglvnd",
  "mesa",
  "glib",
  "ffmpeg",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[start]
# The definitive fix: We prepend the NIXPACKS_LIBS_PATH (provided by the build system)
# to the LD_LIBRARY_PATH at runtime. This is the correct and final way to ensure
# the application can find all of its shared libraries on this platform.
cmd = "LD_LIBRARY_PATH=$NIXPACKS_LIBS_PATH:$LD_LIBRARY_PATH gunicorn app:app --bind 0.0.0.0:$PORT" 