# nixpacks.toml

[phases.setup]
# Use the Nix package manager directly for robust, guaranteed dependency handling.
# This is the definitive solution for providing system libraries on Railway.
nixPkgs = ["mesa", "glib", "libSM", "libXext", "libXrender"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 