# nixpacks.toml

[phases.setup]
# Use the Nix package manager directly for robust, guaranteed dependency handling.
# This configuration provides both the OpenGL library provider (mesa) 
# and the dispatcher (libglvnd) to ensure the library is available at runtime.
nixPkgs = [
  "python312",
  "libglvnd",
  "mesa",
  "glib"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 