# nixpacks.toml

[phases.setup]
# This is a comprehensive and definitive list of system packages required by
# the application, including the Python interpreter and the `steam-run` utility.
nixPkgs = [
  "python312",
  "steam-run",
  "ffmpeg"
]

[start]
# We execute the application inside the `steam-run` FHS environment.
# This is the definitive solution to ensure all shared libraries are found at runtime.
cmd = "steam-run gunicorn app:app --bind 0.0.0.0:$PORT" 