# nixpacks.toml

[phases.setup]
# Use the Nix package manager to build a self-contained FHS environment.
# This is the definitive solution for ensuring the application can find all
# of its native library dependencies at runtime.
nixPkgs = [
  "python311",
  "pkgs.python311.pkgs.build-python-FHS-env",
  "libglvnd",
  "mesa",
  "glib"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 