# nixpacks.toml

[phases.setup]
# A comprehensive and definitive list of system packages required by the application.
nixPkgs = [
  "python312",
  "libglvnd",
  "mesa",
  "glib",
  "ffmpeg",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[start]
# Diagnostic step: Print all environment variables to the log, then attempt to start.
# This will show us the value of NIXPACKS_LIBS_PATH and other critical variables.
cmd = "env && echo '--- Starting Gunicorn ---' && LD_LIBRARY_PATH=$NIXPACKS_LIBS_PATH:$LD_LIBRARY_PATH gunicorn app:app --bind 0.0.0.0:$PORT" 