# nixpacks.toml

[phases.setup]
# A comprehensive and definitive list of system packages required by the application.
nixPkgs = [
  "python312",
  "libglvnd",
  "mesa",
  "glib",
  "ffmpeg",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[start]
# For debugging, we run the Flask development server directly.
# This will confirm if the environment itself is correct, isolating Gunicorn as a variable.
cmd = "python app.py" 