# nixpacks.toml

[phases.setup]
# A comprehensive and definitive list of system packages required by the application.
nixPkgs = [
  "python312",
  "libglvnd",
  "mesa",
  "glib",
  "ffmpeg",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[start]
# The definitive fix: We prepend the standard system library path to the LD_LIBRARY_PATH
# at runtime. This ensures the dynamic linker can find the libraries installed by Nix.
cmd = "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH gunicorn app:app --bind 0.0.0.0:$PORT" 